version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sed -i '/jessie-backports/d' /etc/apt/sources.list
            sed -i '/jessie-updates/d' /etc/apt/sources.list
            apt-get install unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run: 
          name: Validate Packer JSON
          command: packer validate packer.json
      - run:
          name: Build Packer
          command: packer build packer.json

workflows:
  version: 2

  packer_buid:
    jobs:
      - build:
          filters:
            branches:
              only:
                - a7
